apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redis
  labels:
   app: microservices-example
   namespace: distribuidos
spec:
  replicas: 2
  selector:
    matchLabels:
         app: microservices-example
         type: deployment-redis
  template:
    metadata:
      labels:
        app: microservices-example
        type: deployment-redis
    spec:
     containers:
     - name: deployment-redis
       image: redis/redis-stack-server:latest
       ports:
        - containerPort: 6379