apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  namespace: distribuidos
  labels:
   app: microservices-example
spec:
  replicas: 2
  selector:
    matchLabels:
         app: microservices-example
         type: auth-api
  template:
    metadata:
      labels:
        app: microservices-example
        type: auth-api
    spec:
     containers:
     - name: auth-api
       image: jhormanmera/auth-api
       ports:
        - containerPort: 8000